### ISSUE TITLE
Feature Request  : Custom  classes and IDs.

### ISSUE THREAD

**Issue by shashtag** [Atri-Labs/atrilabs-engine#207]
Just like texts in the text box and buttons, each element should have a CustomPropsTree option to add classes and Ids, this would allow customisability to the developers and probably a way to make plugins on top of the editor. In future you could leverage the plugin ecosystem as a marketplace.

**Comment by darshitac11** [comment]
That's a good point, thanks for the suggestion @shashtag! 

We had provided custom classes in our earlier versions but moved away from them for the sake of simplicity and because we hadn't nailed the UX. 

We are adding a rich support for plugins in the upcoming releases next month, most notably the capability to create and use a custom React component library, add custom CSS/JS as plugins, etc. We will also add custom classes again in Nov-Dec.

**Comment by darshitac11** [comment]
Feature request already in roadmap. Hence closing the issue.
