### ISSUE TITLE
Create a calorie tracker app

### ISSUE THREAD

**Issue by darshitac11** [Atri-Labs/atrilabs-engine#246]
Instructions for this issue:

1. Build a calorie tracker web app using Atri framework. 
- This app should be responsive. 
- You can pick any design. 
- Follow the instructions provided [here](https://github.com/Atri-Labs/atrilabs-engine/blob/main/CONTRIBUTING.md#creating-an-atri-app) to create an Atri app.
- You can also refer [this YouTube playlist](https://www.youtube.com/watch?v=p135tfBvdaE&list=PLTQwOMNg4n8CJf2mbF5pJ3A9cEjr1gdRf)

2. Write its backend using Python to:
- take food item as input 
- estimate its calorie contribution
- display all food items consumed 
- display nutrient breakdown

3. Deploy your app using GitHub pages and Atri CLI. You can follow the steps [here](https://docs.atrilabs.com/deploy-app/deploy-ghpages) 

4. Submit a Pull Request (PR).
- Once your PR is merged, your app will be added to the [made-with-atri folder](https://github.com/Atri-Labs/atrilabs-engine/blob/main/made-with-atri/README.md).

**Comment by mhered** [comment]
Can I take this issue for Hacktoberfest?

**Comment by darshitac11** [comment]
Sure! I have assigned it to you. 

Let us know if you have any questions.

**Comment by mhered** [comment]
Hello Madam,
I am struggling with the framework. I made a super simple Home page with a table inside a div and I cannot get it to render, I get the following error: 
```
TypeError: Cannot read properties of undefined (reading 'height')
    at eval (webpack://getAppText/./node_modules/@atrilabs/react-component-manifests/src/manifests/Table/Table.tsx?:34:66)
    at renderWithHooks (webpack://getAppText/./node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js?:5461:16)
    at renderForwardRef (webpack://getAppText/./node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js?:5645:18)
    at renderElement (webpack://getAppText/./node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js?:5808:11)
    at renderNodeDestructive (webpack://getAppText/./node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js?:5888:11)
    at renderNode (webpack://getAppText/./node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js?:6022:12)
    at renderHostElement (webpack://getAppText/./node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js?:5446:3)
    at renderElement (webpack://getAppText/./node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js?:5755:5)
    at renderNodeDestructive (webpack://getAppText/./node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js?:5888:11)
    at renderForwardRef (webpack://getAppText/./node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js?:5662:5)
``` 
I created however a second page with a few text boxes and a submit button and this one renders well.

**Comment by mhered** [comment]
I see it may be related to issue #396

**Comment by mhered** [comment]
Hello @darshitac11 I managed to solve the initial issues and uploaded a first very basic version to github: https://github.com/mhered/calcount3 and a demo to GH pages: https://mhered.github.io/calcount3/
It is still in early development but I am stuck again and need help.

My intention was to select a food item from the dropdown menu, and add it to the table with the Add button. It seems that the button onClick event is not activated tough. I read the docs and looked at the examples but I cannot find what I am doing wrong. Your help would be much appreciated...

Below the relevant extract from [../controllers/routes/main.py](https://github.com/mhered/calcount3/blob/main/controllers/routes/main.py):
```python
[...]
def handle_event(at: Atri, req: Request, res: Response):
    """
    This function is called whenever an event is received. An event occurs when user
    performs some action such as click button.
    """
    
    if at.Button1.onClick:
        at.Button1.custom.text == "Added" # Added to check if onClick event is activated
        # get food selected in Dropdown1
        food_item = next(
            (item for item in FOODS if item['name'] == at.Dropdown1.custom.selectedValue),
             None)
        # add row
        at.Table1.custom.rows.append(food_item)
[...]
```

**Comment by darshitac11** [comment]
@mhered - I've used onclick events for button in my other projects and it seemed to work then. 

Anyways, I'll clone your repo and try it first at my end and get back to you.

**Comment by mhered** [comment]
Hello @darshitac11 I managed to get it to work - partially. The problem was with my code. Now the button responds to `onClick` events and I am able to add elements as text to a `TextBox` field, however I don't know how to append them to the `Table` element: `at.Table1.custom.rows.append(food_item)` does not work.

The relevant extract from [../controllers/routes/main.py](https://github.com/mhered/calcount3/blob/main/controllers/routes/main.py):

```python

def handle_event(at: Atri, req: Request, res: Response):
    """
    This function is called whenever an event is received. An event occurs when user
    performs some action such as click button.
    """

    if at.Button1.onClick:
        at.TextBox2.custom.text = f"Selected: {at.Dropdown1.custom.selectedValue}"
        # get food selected in Dropdown1
        food_item = [item for item in FOODS if item['name'] == at.Dropdown1.custom.selectedValue]
        # add row
        if food_item:
            at.TextBox3.custom.text+=f"\t{food_item[0]}"
            at.Table1.custom.rows.append(food_item[0]) 
```
I updated the repo: https://github.com/mhered/calcount3 , and added below as well a screenshot of the behavior of the app as it is today: after adding 3 food items, they show in the TextBox but not on the Table. Any ideas what I am doing wrong?

![Screenshot from 2022-10-17 22-14-57](https://user-images.githubusercontent.com/75589082/196274461-180496f4-fdb0-4650-b217-993b2e6897a0.png)

**Comment by cruxcode** [comment]
@mhered Thanks for reaching out with this issue. I realize we have not done a very good job of documentation and preparing video tutorials for complicated components like Table. We are determined to improve fast.

I took a clone of your app and tried the following:
```python
def handle_event(at: Atri, req: Request, res: Response):
    """
    This function is called whenever an event is received. An event occurs when user
    performs some action such as click button.
    """
    
    if at.Button1.onClick:
        at.TextBox2.custom.text = f"Selected: {at.Dropdown1.custom.selectedValue}"
        # get food selected in Dropdown1
        food_item = [item for item in FOODS if item['name'] == at.Dropdown1.custom.selectedValue]
        # add row
        if food_item:
            at.TextBox3.custom.text+=f"\t{food_item[0]}"
            at.Table1.custom.rows.append(food_item[0])

            # NOTE: recommended changes are made below
            at.Table1.custom.rows = at.Table1.custom.rows
```

In the code snippet that I shared above, there is just one small change:
1. I added one line at the end of the code that assigns `at.Table1.custom.rows` to itself. This obviously feels like a hack but it has some reasoning behind this. The reason is that we want the payload from the server to the browser to be as small as possible. The way this optimization works is that we try to detect all the fields that you have `set`. By doing just `at.Table1.custom.rows.append(food_item[0])`, you are doing a `get` on `at.Table.custom.rows`, hence, to force a `set` call to `rows` field, I just reassigned it to itself. We have a few ideas on how to improve the design and make the python integration even more intuitive. We will soon setup a working group that will recommend changes to the design of python API. We will share the invite to join the working group for designing Python API in Slack, hence, if you would be interested, please join the working group.

**Comment by mhered** [comment]
Hello @darshitac11 @cruxcode ,
I created a simple calorie tracker app and uploaded it to github 
The app lets you select food items from the Dropdown menu and click the **Add** button to add them to the table. The app then updates the table with the content of calories and nutrients of the foods consumed during the day and also updates the graph with the total intake of nutrients and calories during the last 7 days.
Kindly review it and let me know if it is in line with your expectations. Also, as I am participating in Hacktoberfest, kindly let me know where/how to do a PR to your repo with the proposed app.

Repo: https://github.com/mhered/calcount4
Static demo in GH pages: https://mhered.github.io/calcount4/
GIF:
![calories](https://user-images.githubusercontent.com/75589082/197424360-a63409ef-8c2a-41f0-860e-680eee802764.gif)

**Comment by mhered** [comment]
I created PR #452 to close this issue.
